### ISSUE TITLE
Roadmap for release v1.0.0

### ISSUE THREAD

**Issue by jprivet-dev** [jprivet-dev/bootstrap-dark-mode#4]
- [x] Complete the documentation
    - [x] How use variables
    - [x] npm commands
    - [x] Add ressources https://www.pinterest.fr/jeanphilipperivet/ui-dark/
    - [x] Add an screenshot
- [x] Complete the examples
    - [x] Navigations
    - [x] Other elements
- [x] Remove unnecessary core-js
